### ISSUE TITLE
49e1c89 breaks the "Filter revisions" form in revision history page / 页面历史的“过滤修订版本”表单跳转到无效的URL

### ISSUE THREAD

**Issue by csalinezh** [wikimedia-gadgets/VariantAlly#14]
Steps to reproduce:
1. Open https://zh.wikipedia.org/w/index.php?title=Wikipedia%3A%E9%A6%96%E9%A1%B5&action=history
2. Expand the form for filtering revisions. Click the submit button.

The user will be redirected to https://zh.wikipedia.org/[object%20HTMLInputElement]?title=Wikipedia%3A%E9%A6%96%E9%A1%B5&date-range-to=&tagfilter=&action=history, clearly a 404 page.

---
The issue appears to have been introduced in https://github.com/wikimedia-gadgets/VariantAlly/commit/49e1c898f30adfaaf16b891b04bc1d5b491ea604. The code uses `form.action` to access the URL for submission: https://github.com/wikimedia-gadgets/VariantAlly/blob/c364f4afe62938ecf1b696069a9cb646425ba3c6/gadgets/variant-ally/src/controller.ts#L187-L189

However, the `<form>` contains an `<input name="action">` (due to the mediawiki `index.php` parameter scheme). The `action` property of the form object thus points to the `<input>` element, not the reflected attribute.

**Comment by diskdance** [comment]
Oops, sadly TypeScript failed to catch this issue. Looking into it.

**Comment by diskdance** [comment]
Should be fixed on both [Chinese Wikipedia Beta Cluster](https://zh.wikipedia.beta.wmcloud.org/) and the [production site](https://zh.wikipedia.org/w/index.php?title=MediaWiki:Gadget-VariantAlly.js&diff=prev&oldid=88217684). Please check.

**Comment by csalinezh** [comment]
Unfortunately the fix is half-done. `rewriteLink()` still gets URL as `form.action` (the child `<input>` element) instead of `submitUrl`: https://github.com/wikimedia-gadgets/VariantAlly/blob/0966f885a722e072c915d6ea9bb6fcd348737a62/gadgets/variant-ally/src/controller.ts#L192

Writing to `form.action` does change the attribute of `<form>`, likely due to some weird HTML-DOM interface rule ([`HTMLFormControlsCollection`](https://html.spec.whatwg.org/multipage/common-dom-interfaces.html#htmlformcontrolscollection) only defines getter. It would be even weirder if it can replace the child element with a string).

I also see someone using introspection (`Object.getOwnPropertyDescriptor(HTMLFormElement.prototype, 'action')`) to access it through JS object property [here](https://stackoverflow.com/a/65066146). That might be useful if the goal is to avoid resolving relative URL (`form.action` always returns absolute URL), but it's probably irrelevant here.

**Comment by diskdance** [comment]
Thank you for the feedback! I've deployed the new patch on both wikis. Can you please check again whether it is working correctly now?

**Comment by csalinezh** [comment]
Glad to learn that the query string is replaced for `<form method="get">` (https://github.com/wikimedia-gadgets/VariantAlly/commit/85cd7250eb602b00c04b85a275a2db9da6be7968). I also missed this point.

It now works correctly. As a good side effect, the search result page also receives variant conversion. Thank you for the work!

Though I might be too picky here, I notice that the behaviour of searching changes a bit for browsers already configured with Chinese languages. The `variant` parameter is added unconditionally without regard to the logic about `normalizationTargetVariant` in `rewriteLink()`. However the impact should be minimal as probably all of those pages exist transitively (search result URLs are unlikely to be copied and shared). It should be ignorable unless other breakage surfaces.

**Comment by csalinezh** [comment]
I just noticed that due to bfcache, the `<input name="variant">` is kept as is when user uses the "Back" button. Therefore when the user makes another search request in the previous page, another `<input name="variant">` will be inserted. This results in an extra `&variant=` in the URL.

However it does not break mediawiki, due to php `$_GET` keeping only the last occurrence of repeated parameters (ref. https://www.php.net/manual/en/faq.html.php#faq.html.arrays).
